### ISSUE TITLE
Chrome 67.0.3396.99

### ISSUE THREAD

**Issue by petersori** [elliotwaite/youtube-thumbnail-rating-bar#1]
It seems that version 0.0.8 is not working in Chrome 67.0.3396.99:
- Icon looks gray in the menu
- Extension reports no errors
- There is no ratings bar in YouTube

**Comment by elliotwaite** [comment]
Hmm. I'll look into this and get back to you. Thanks for letting me know.

**Comment by elliotwaite** [comment]
Just released version 0.0.10. You should be able to see the icon in the toolbar in color now. And when you click it, it should show an options pop-up window. Let me know if this update works better for you, or if you still aren't seeing the rating bars.

**Comment by petersori** [comment]
I can confirm that the changes worked.
Had to remove old extension and install new version, that gave the icon color and Optios menu.
After the browser restart bars under the YouTube video thumnails are now shown as expected.
