### ISSUE TITLE
Bar doesn't show up on videos you've watched

### ISSUE THREAD

**Issue by Liz-chan** [elliotwaite/youtube-thumbnail-rating-bar#2]
The rating bar doesn't show up if the red bar indicating you've seen the video is already there, which the old extension got around by moving that bar to the top. This is the bar that I'm talking about.
![image](https://user-images.githubusercontent.com/18467466/42050778-ddc805fe-7ad7-11e8-93be-f3d096b9c783.png)

**Comment by elliotwaite** [comment]
Thanks for pointing that out. I had my watch history turned off. Should be fixed now in the latest version: 0.0.15. If it's still not working for you, let me know.

**Comment by elliotwaite** [comment]
And thanks for posting that screenshot, that was helpful.

**Comment by Liz-chan** [comment]
Yea it works now, thanks!

**Comment by elliotwaite** [comment]
👍
