### ISSUE TITLE
Feature Request - Opacity

### ISSUE THREAD

**Issue by samfriedmann** [elliotwaite/youtube-thumbnail-rating-bar#6]
Please add the opacity adjustment features of the original extension. (So we can make the bar 70% opaque for example to see through a little)

**Comment by elliotwaite** [comment]
Sam, thanks for the feature request. I'll add that in the next update, which should be finished within a week. I'll let you know here when it's been released.

**Comment by elliotwaite** [comment]
Just released the update that includes the option to change the opacity. Thanks again for requesting this feature. Let me know if it is working for you.

**Comment by samfriedmann** [comment]
Sounds good, man. Thanks for your hard work to put this thing back
together. I'm not at my computer today, but I'll test it tommorow to see
how it works and let you know.
