### ISSUE TITLE
Bug: Ratings bar turns blue when you like a video

### ISSUE THREAD

**Issue by Liz-chan** [elliotwaite/youtube-thumbnail-rating-bar#7]
Kind of self-explanatory, here's a screenshot.
![image](https://user-images.githubusercontent.com/18467466/43001297-c2e0f56c-8bf2-11e8-98ca-ce47ae75439e.png)
![image](https://user-images.githubusercontent.com/18467466/43001301-c84c9cc2-8bf2-11e8-987b-fd873309911b.png)

**Comment by elliotwaite** [comment]
Ah, missed that. Thanks for pointing that out. It'll be fixed in the next update. I'm in the middle of adding some other features, though, so it might be a few days before that next update is released. But I'll post a message here when it's been updated.

**Comment by elliotwaite** [comment]
Just released an update that included the fix for this issue. Thanks again for reporting it.
